const puppeteer = require('puppeteer');
(async () => {
  const browser = await puppeteer.launch({ headless: true, args: ['--no-sandbox', '--disable-setuid-sandbox'] });
  const page = await browser.newPage();
  await page.setViewport({ width: 1440, height: 900 });
  console.log('navigating...');
  await page.goto('http://localhost:3000', { waitUntil: 'networkidle0', timeout: 20000 });
  console.log('waiting for loader...');
  await new Promise(r => setTimeout(r, 8000));
  await page.screenshot({ path: 'C:/Users/victo/Desktop/s1-hero.png' });
  console.log('hero captured');
  await page.evaluate(() => window.scrollBy(0, 800));
  await new Promise(r => setTimeout(r, 1500));
  await page.screenshot({ path: 'C:/Users/victo/Desktop/s2.png' });
  await page.evaluate(() => window.scrollBy(0, 1600));
  await new Promise(r => setTimeout(r, 1500));
  await page.screenshot({ path: 'C:/Users/victo/Desktop/s3.png' });
  await page.evaluate(() => window.scrollBy(0, 3000));
  await new Promise(r => setTimeout(r, 1500));
  await page.screenshot({ path: 'C:/Users/victo/Desktop/s4.png' });
  await page.evaluate(() => window.scrollBy(0, 5000));
  await new Promise(r => setTimeout(r, 1500));
  await page.screenshot({ path: 'C:/Users/victo/Desktop/s5.png' });
  await page.evaluate(() => window.scrollBy(0, 8000));
  await new Promise(r => setTimeout(r, 1500));
  await page.screenshot({ path: 'C:/Users/victo/Desktop/s6.png' });
  await browser.close();
  console.log('done');
})().catch(e => { console.error(e); process.exit(1); });
