// Dados de cada case. Mesmo template para todos — só muda o conteúdo aqui.
// Copy de todos os cases aprovada (vistoria de copy 2026-07).
export const CASES = {
  "hawk-street": {
    tags: ["E-COMMERCE", "STREETWEAR", "2026"],
    title: "HAWK",
    desc: "Loja de streetwear construída para converter. Uma experiência de compra que carrega a identidade da marca em cada detalhe.",
    challenge: "Levar a Hawk Street além do Instagram, hoje seu principal canal de vendas, para uma loja própria com mais credibilidade e alcance — atraindo mais tráfego e novos clientes, sem deixar de lado quem já acompanha a marca.",
    solution: "Uma loja construída como vitrine da marca, que traduz no digital o visual editorial da Hawk Street — forte, minimalista e premium — e entrega uma experiência de compra fluida e profissional, à altura da presença que a marca já tem.",
    results: "Com a loja no ar, a Hawk Street vende pelo próprio canal e fortalece sua marca, com estrutura para crescer e escalar as vendas.",
    blocks: [
      {
        type: "compare",
        before: "/cases/hawk-street/hero-antigo.png",
        after: "/cases/hawk-street/hero-novo.png",
        beforeAlt: "Home antiga da Hawk Street — template básico de loja",
        afterAlt: "Home nova da Hawk Street — redesign editorial e premium",
        beforeLabel: "",
        afterLabel: "",
        mockup: "/cases/hawk-street/notebook-mockup.png",
        title: "A primeira impressão, refeita.",
        description: "Onde a home antiga abria escura e sem direção, o novo hero abre como uma campanha — editorial, minimalista, com um convite direto para explorar a coleção. Menos ruído, mais presença: a autoridade que uma marca de streetwear precisa transmitir logo no primeiro segundo.",
        caption: "Arraste para comparar o antes e o depois.",
      },
      {
        type: "reveal",
        image: "/cases/hawk-street/quick-view-wide.png",
        imageMobile: "/cases/hawk-street/quick-view.png",
        alt: "Quick-view de produto aberto sobre o catálogo da Hawk Street",
        ratio: "1665 / 947",
        mobileRatio: "813 / 947",
        revealInset: 57,
        title: "Da vitrine pra sacola.",
        body: "Na loja antiga, ver um produto era abrir outra página. Aqui, um clique abre um quick-view elegante — fotos, cor, tamanho e adicionar à sacola — sem perder o embalo da navegação. Menos cliques, menos atrito, mais compra.",
      },
      {
        type: "showcase",
        image: "/cases/hawk-street/catalogo.png",
        alt: "Página de catálogo da Hawk Street — filtros laterais e grade de produtos",
        ratio: "1125 / 934",
        title: "Tudo no lugar certo.",
        body: "Categoria, coleção, tamanho, cor, preço — o cliente filtra e encontra em segundos. E cada produto já se vende no próprio card: promoção, novidade, últimas unidades. Onde o template genérico só empilhava itens, a Hawk Street virou uma vitrine curada de verdade.",
      },
      {
        type: "cta",
        title: "Curtiu esse projeto?\nBora criar o seu.",
        body: "Quer uma loja que vende como essa — ou algo no seu estilo? É só me chamar.",
        buttonLabel: "Bora!",
        buttonHref: "https://wa.me/5533984246770",
      },
    ],
  },

  "minas-tintas": {
    tags: ["APP", "FIDELIDADE", "2026"],
    title: "MINAS TINTAS",
    desc: "Um programa de fidelidade pros pintores que trabalham com a Minas Tintas. Cada orçamento que eles fecham com a loja vira pontos — e os pontos viram prêmios numa lojinha exclusiva.",
    challenge: "A Minas Tintas quis sair na frente: criar um programa próprio pra recompensar os pintores que levam venda pra loja. A ideia era registrar cada indicação e devolver isso pro pintor em pontos e prêmios — fortalecendo a parceria com quem ajuda a loja a crescer.",
    solution: "O app tem dois lados: no do pintor, ele monta os orçamentos; no da loja, a equipe confirma os pagamentos. A cada aprovação, o sistema credita os pontos pro pintor — que depois troca por prêmios numa lojinha exclusiva gerenciada pela loja.",
    results: "Todo o fluxo de indicação e bônus num lugar só, fácil de acompanhar. A loja ajusta as regras do jeito que quiser e tem base pronta pra crescer a rede de pintores.",
    blocks: [
      {
        type: "shot",
        image: "/cases/minas-tintas/desktop-admin.png",
        alt: "Painel administrativo do Minas Tintas — tela de pedidos para aprovação",
        ratio: "2391 / 1426",
        captionTop: true,
        label: "Painel admin",
        caption: "Aprova pedidos e libera bônus em poucos cliques.",
      },
      {
        type: "split",
        image: "/cases/minas-tintas/pintor-app.png",
        alt: "App do pintor Minas Tintas — home e lojinha de pontos",
        ratio: "1024 / 1536",
        title: "Orçou, ganhou, trocou.",
        body: "O pintor monta o orçamento em poucos cliques e acompanha tudo pelo celular. E cada ponto acumulado vira prêmio de verdade: ferramenta, material e brinde da marca.",
      },
      {
        type: "cta",
        title: "Curtiu esse projeto?\nBora criar o seu.",
        body: "Você pode ter um sistema como esse — ou algo pensado só pro seu negócio. É só me chamar.",
        buttonLabel: "Bora!",
        buttonHref: "https://wa.me/5533984246770",
      },
    ],
  },

  "barbearia": {
    tags: ["AGENDAMENTO", "SISTEMA", "2026"],
    title: "BARBEARIA",
    desc: "Sistema de agendamento inteligente para barbearias. O cliente marca o horário em poucos passos e a barbearia gerencia profissionais, agenda num painel próprio.",
    challenge: "O barbeiro recebe muitos clientes pelo WhatsApp ao mesmo tempo e não consegue parar de cortar cabelo para responder todos. E ainda precisa controlar a agenda de vários profissionais, os horários livres e os agendamentos. O desafio é atender bem o cliente, desafogar o barbeiro e manter a operação organizada — tudo num sistema só.",
    solution: "O cliente marca em poucos passos, pelo site ou pelo WhatsApp, e vê apenas os horários realmente livres — calculados a partir da agenda de cada profissional, folgas e bloqueios. No WhatsApp, parte do atendimento é automática e já sugere o próximo horário, então o barbeiro não precisa parar de trabalhar para responder. E um painel reúne tudo: o calendário de todos os profissionais, as conversas pendentes e um dashboard com ocupação, horários de pico e disponibilidade.",
    results: "O barbeiro não para mais de trabalhar para responder mensagem: o cliente agenda sozinho, a qualquer hora, pelo site ou pelo WhatsApp. A agenda fica organizada e sem conflito, e o barbeiro acompanha o dia inteiro — ocupação, horários livres e conversas pendentes.",
  },

  "flux-time": {
    tags: ["APP", "FOCO", "2026"],
    title: "FLUX TIME",
    desc: "Aplicativo de foco e produtividade construído para concentração profunda. Um timer Pomodoro com display flip-clock, modo imersivo que apaga toda a interface e sons ambientes para o usuário entrar no fluxo.",
    challenge: "Os aplicativos de produtividade costumam colocar muita coisa na mesma tela. Quando listas, controles e informações aparecem todos juntos, fica difícil até entender por onde começar. Criei o Flux Time para mudar essa lógica e deixar o usuário concentrado na tarefa que escolheu fazer.",
    solution: "No Flux Time, você define o tempo que tem e a tarefa que quer fazer. Na hora de configurar a sessão, também pode escolher uma trilha para acompanhar aquele momento e ajudar na concentração. Os ciclos de foco e pausa organizam a sessão, enquanto as tarefas e anotações ficam ali para você retomar depois. Com tudo no mesmo lugar, o dia continua organizado sem precisar alternar entre várias ferramentas.",
    results: "Trabalho, estudo e tarefas do dia ficam mais simples de conduzir quando a tela mostra apenas o que precisa estar ali. O Flux Time foi pensado para tirar o excesso do caminho e deixar sua atenção naquilo que você decidiu fazer. Com menos coisa disputando espaço, fica mais fácil manter o ritmo.",
    blocks: [
      {
        type: "shot",
        video: "/cases/flux-time/abertura.mp4",
        alt: "Abertura do Flux Time até a entrada no modo foco",
        ratio: "16 / 9",
        framed: true,
        ambientGlow: "red",
        captionTop: true,
        label: "Tela principal",
        captionSeparator: " ",
        caption: "Em poucos cliques, você define seu fluxo e começa a tarefa no seu ritmo.",
      },
      {
        type: "split",
        image: "/cases/flux-time/configurar-ciclos.png",
        alt: "Pessoa configurando os ciclos de foco do Flux Time em um tablet na escrivaninha",
        ratio: "4 / 3",
        variant: "photo",
        mediaSize: "wide",
        rounded: true,
        entrance: true,
        textAlign: "left",
        contentGap: "wide",
        title: "Você define o ritmo.",
        body: "Você escolhe quantos ciclos quer fazer e ajusta o tempo de foco e de pausa conforme a tarefa. A sessão acompanha o tempo que você tem, seja para estudar ou organizar o restante do dia.",
      },
      {
        type: "split",
        image: "/cases/flux-time/tarefas-na-rua.png",
        alt: "Pessoa acompanhando as tarefas do Flux Time pelo celular na rua",
        ratio: "848 / 1264",
        variant: "photo",
        mediaSize: "compact",
        rounded: true,
        entrance: true,
        reverse: true,
        title: "Seu dia, na palma da mão.",
        body: "Na rua, no intervalo ou onde você estiver, o Flux Time mantém suas tarefas por perto. Acompanhe a semana, registre uma anotação e não deixe o que importa escapar.",
      },
      // CTA único: aqui o fechamento é TESTAR o produto (case de produto próprio).
      // Sem bloco de contato — o "Contato" da nav cai no fallback /#contato.
      {
        type: "cta",
        title: "Quer entrar no foco?\nTesta você mesmo.",
        body: "O Flux Time está no ar — abre, dá o play e sente a diferença.",
        buttonLabel: "Usar o Flux Time",
        buttonHref: "https://rel-gio-taupe.vercel.app/",
      },
    ],
  },

  "art-piso": {
    tags: ["GESTÃO", "ESTOQUE", "2026"],
    title: "ART PISO",
    desc: "Sistema de controle de estoque para depósito de pisos. Cada caixa tem lugar, dono e destino — e o que sobra pra vender é sempre calculado, nunca digitado à mão.",
    challenge: "Um galpão cheio de piso e nenhuma certeza. Com centenas de lotes espalhados, controlar no papel significa não saber o que realmente dá pra vender — nem onde está cada caixa na hora de entregar.",
    solution: "Um sistema onde a caixa é a fonte da verdade. Ele sabe onde cada uma está, quanto já tem dono e quanto sobra pra vender. Funciona no computador da loja, no tablet do balcão e no celular de quem está no galpão.",
    results: "A loja passa a saber, em tempo real, o que tem e o que pode prometer. E o sistema avisa antes do problema: quando um produto está acabando ou quando um pedido está perto da data sem caixa suficiente.",
    blocks: [
      {
        type: "shot",
        image: "/cases/art-piso/estoque.png",
        alt: "Tela de estoque do Art Piso — métricas do galpão e lista de produtos por lote",
        ratio: "2880 / 1800",
        framed: true,
        captionTop: true,
        label: "Tela de estoque",
        caption: "O que existe no galpão e o que dá pra vender nunca são o mesmo número. Aqui os dois aparecem lado a lado.",
      },
      {
        type: "split",
        image: "/cases/art-piso/tablet-showroom.png",
        alt: "Vendedor consultando as reservas do Art Piso no tablet, no showroom da loja",
        ratio: "848 / 1264",
        variant: "photo",
        rounded: true,
        entrance: true,
        title: "No balcão, na mão de quem vende.",
        body: "O mesmo sistema roda no tablet da loja e no celular de quem está no galpão. O vendedor consulta o que tem e o que já tem dono sem sair de perto do cliente.",
      },
      {
        type: "split",
        image: "/cases/art-piso/celular-alertas.png",
        alt: "Alertas do Art Piso no celular — encomenda em risco, produto esgotado e estoque baixo",
        ratio: "1112 / 746",
        variant: "photo",
        reverse: true,
        rounded: true,
        entrance: true,
        title: "Avisa antes de dar problema.",
        body: "Encomenda com a data chegando e caixa faltando, produto no fim, perda registrada. O aviso chega enquanto ainda dá tempo de resolver — não quando o cliente já está na loja.",
      },
      {
        type: "cta",
        title: "Curtiu esse projeto?\nBora criar o seu.",
        body: "Tem um estoque, um galpão ou uma operação que ainda vive no papel? É só me chamar.",
        buttonLabel: "Bora!",
        buttonHref: "https://wa.me/5533984246770",
      },
    ],
  },
};
